### PR TITLE
Switch to mailman3

### PR DESCRIPTION
**Pull request by tobald**
This branch adds support for mailman 3. Existing mailman 2 mailing lists continue to work as before, with an additional button to trigger per-list migrations to mailman3. This was tested on debian buster, optionnally with mailman packages backported from bullseye. Koumbit-patched installations should work as well. Please refer to git history for full changeset.

### CODE REVIEW

**Comment by camlafit** [comment]
Hello

Looks a great job. Now is to do a review. I hope to do it no too late

Thanks

**Comment by tobald** [comment]
Hi,

I just pushed an updated branch here with miscellaneous fixes. Meanwhile I see
@kienanstewart made other changes, this is nice, but things need to be sorted/resolved.

**Comment by tobald** [comment]
Please ignore my previous comment.

Branch is now ready for review, we deployed it at domainepublic.

Thanks dachari for his inspiring notes : https://forum.chatons.org/t/experience-de-migration-de-mailman2-a-mailman3/

**Comment by tobald** [comment]
Note I released packages at https://tobald.eu.org/debian/

(the buster-backports repository is optional)

**Comment by camlafit** [comment]
Hello

Thanks a lot to continue this project.
We plan to integrate this version in next release as we can't use anymore python2 with actual debian version.

Thanks

**Comment by camlafit** [comment]
Notice : I've not forgotten. I'm a bit on delay sorry
thanks a lot again

**Pull request closed without merging**
