### PR TITLE
Fix #14: Use a local domain reverse proxy for accessing mailman

### LINKED ISSUE #14: Utilser une configuration de proxy d'apache2 pour éviter de patcher et distribuer mailman
Le mode itk (apache roule sous le uid de l'utilisateur et le panneau sous le uid 1999) dans la configuration par défaut d'AlternC. Ceci ne permet pas l'exécution des cgi de mailman par l'interface web d'apache.  C'est une patch dans Debian qui limite l'éxécution à un certain uid d'utilisateur du système.

voici la patch chez debian
https://sources.debian.org/src/mailman/1:2.1.23-1+deb9u2/debian/patches/10_wrapper_uid.patch/

Il y a 2 options:

1. Recompiler mailman et retirer la patch de debian. C'est pas génial de faire la maintenance de ça pour plusieurs raisons, ça demande un suivi des fix de sécurité chez Debian et faire des backports de celles-ci...

2. Faire une configuration dans Apache2 pour l'accès aux cgi par proxy. De plus, 2 autres configurations doivent être fait dans le mm_cfg.py de Mailman.

On prèfère de loin la deuxième option.

Un PR va arrive pour implanter la deuxième option.

Ce problème a été discuté longuement ici :  AlternC/AlternC#15

De plus, un détail a été ajouté ici #6

### PR DESCRIPTION
**Pull request by kienanstewart**
By default alternc panel runs as a uid which is not accepted by the
debian version of mailman. This takes any requests are proxies it
through mailman.localdomain which runs as the default www-data user.

Refs #14

### CODE REVIEW

**Comment by camlafit** [comment]
Must wait ssl-feature branch on Alternc project as https use is configured

**Comment by kienanstewart** [comment]
I didn't notice the change to the default url to https:// instead of http://. I'd be fine merging without that change. I don't think it's required to make anything work. Want me to push a commit that changes it back?

**Comment by camlafit** [comment]
Hello

I you could clean about https use and check conflict on mm_cfg.py (I presume related since merge #15 )

**Comment by kienanstewart** [comment]
Hi, I merged in the recent changes and switched the default list URL back to HTTP.

**Comment by sebas891** [comment]
J'avais activé le https dans mm_cfg.py parce sinon la gestion de la modération dans l'interface web de mailman ne fonctionnait pas. Il faut dire que j'ai testé sur une installation qui a une redirection automatique vers https pour le bureau.
Pas de problème pour ne pas activer le https dans ce merge.

**Pull request closed without merging**
